### PR TITLE
Added noarch build

### PR DESCRIPTION
**Pull request by Marco-Sulla**
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* ? [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Marco-Sulla** [comment]
I don't understand. It seems it continues to build a noarch package for every architecture...
Have I to try and merge? What do you suggest?

**Comment by ltalirz** [comment]
Let me ask the experts on https://gitter.im/conda-forge/conda-forge.github.io what the suggested route is

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
> continues to build a noarch package for every architecture...

yep: the multi-output approach will always build all of them. It's possible to use some jinja magic, to force just one build by e.g. 

```yaml
{% set build_noarch = False %}
{% set build_noarch = True %}  # [some selector]
...
outputs:
  {% if build_noarch}
  - name: frozendict-noarch
    ...
  {% endif %}
```

But.... what is the motivation here? A downstream that needs `frozendict` would not be satisfied with `frozendict-noarch`.

It is _possible_ to build multiple, like-named packages by changing _something else_ (usually the build number) but this can be more confusing, and usually reserved for packages that would help _lots_ of other packages stay `noarch: python`... but usually, if there is a performance-related compiled component, it's worth keeping that as the preferred default, if at all possible.

**Comment by Marco-Sulla** [comment]
Ok, thank you ltalirz and bollwyvl, I think I'll merge as-is :)

**Comment by Marco-Sulla** [comment]
Excuse me, yesterday was late and I didn't understand what you wrote. The fact is that if I name a build frozendict-noarch, the wheel will have this name, right? So the only chance I have is to change the build number? It will not reset to zero by the bot? This way I'll have a frozendict-VERSION-py3-none-any.whl, or it will create a noarch wheel for every py version?

**Comment by bollwyvl** [comment]
> name a build frozendict-noarch, the wheel will have this name, right? 

Yes, this yielded:
- https://anaconda.org/conda-forge/frozendict-noarch/files?version=2.2.1

and one would have to `conda install -c conda-forge frozendict-noarch` to get this file. it could even be installed _next to_ `frozendict`, with... unpredictable results.

> only chance I have is to change the build number?

Well... it's the "build string" which is usually made of the build number and a semi-opaque hash which includes things like the compiler used. the python major, for historical reasons, also shows up.

> It will not reset to zero by the bot

If one ["colors within the lines,"](https://github.com/regro/cf-scripts/blob/85e03013bc2beb78dc6cf7d0b0c660e028fac588/tests/test_yaml/version_python_correct.yaml) it can still figure things out... a variable named `build_number` appears to get used. 

> noarch wheel for every py version?

Yes, this is currently creating a `noarch` wheel for each with _slightly_ different hashes, but otherwise no differences... as none of them have any dependencies (other than `python`), _which_ one gets installed is undefined.

Which again begs the question: _why_ do you want `noarch` packages, in addition to per-python-per-platform builds?

**Comment by Marco-Sulla** [comment]
Good question. The answer is simple: noarch build supports Python 3.6+ on every OS that can run Python. The other builds supports Linux, Windows and MacOS and Python 3.7 - 3.10

**Comment by Marco-Sulla** [comment]
Well, I tried as you suggested in this pull request:
https://github.com/conda-forge/frozendict-feedstock/pull/28/files
It didn't build the package for python 3.10 on Linux. It seems that if the output has the same name, the highest build number "wins".

**Pull request merged**
