### PR TITLE
MNT: rerender

### LINKED ISSUE #3: @conda-forge-admin, please rerender
~~Do I need to be a maintainer to trigger this?~~ nope
@conda-forge-admin, please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #3.

Here's a checklist to do before merging.
- [x] Bump the build number if needed.

Fixes #3

### CODE REVIEW

**Comment by ltalirz** [comment]
@tkelman Just for me to understand: is this just about re-rendering the feedstock?
In this case, bumping the build number would seem like the right thing to do...

**Comment by tkelman** [comment]
Yep, we're noticing no build is available for python 3.7 which was causing some downstream issues in the autotick bot that happens to depend on this package. I believe rerendering should fix that, and you're correct that bumping the build number would be a good idea since the upstream package version isn't changing. Thanks for the quick response!

**Comment by ltalirz** [comment]
Let me know in case any problems remain

**Comment by tkelman** [comment]
Will do! Now I'm seeing why there wasn't a noarch build of this available, the merge commit failed on circle (https://circleci.com/gh/conda-forge/frozendict-feedstock/5?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) due to an out of date token, the token update commit had [ci skip], and there hadn't been any other commits until just now.

**Pull request merged**
